version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
        - "3306:3306"
    expose:
        - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'StronGPa$$W0rd!'
    volumes:
        - ./MySQL/MySQL-Preparation.sql:/docker-entrypoint-initdb.d/setup.sql
  web:
    build: ./Flask/
    expose:
        - 9000
    ports:
      - "9000:9000"